services:
  postgres:
    image: postgres:15
    container_name: sol-e-lua-postgres
    environment:
      POSTGRES_DB: sol_e_lua
      POSTGRES_USER: sol_e_lua
      POSTGRES_PASSWORD: sol_e_lua
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: sol-e-lua-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
